service: aws-nodejs # NOTE: update this with your service name

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-west-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:*
      Resource: "*"
    -  Effect: "Allow"
       Action:
         - "s3:ListBucket"
       Resource: "*"
    -  Effect: "Allow"
       Action:
         - "s3:PutObject"
       Resource: "*"

functions:
   [FUNCTION_NAME]:
      handler: index.handler
      events:
        - alexaSkill
      environment:
        APP_ID: "[ALEXA_SKILL_ID]"
        APP_NAME: "[FUNCTION_NAME]"
