export default {
  ASK: ':ask',
  ASK_WITH_CARD: ':askWithCard',
  ASK_WITH_LINK_ACCOUNT_CARD: ':askWithLinkAccountCard',
  TELL: ':tell',
  TELL_WITH_CARD: ':tellWithCard',
  TELL_WITH_LINK_ACCOUNT_CARD: ':tellWithLinkAccountCard',
  CONFIRM: ':confirmSlot',
  CONFIRM_WITH_CARD: ':confirmSlotWithCard',
  CONFIRM_INTENT: ':confirmIntent',
  CONFIRM_INTENT_WITH_CARD: ':confirmIntentWithCard',
  ELICIT: ':elicitSlot',
  ELICIT_WITH_CARD: ':elicitSlotWithCard',
  SAVE: ':saveState',
  DELEGATE: ':delegate',
};
